# Generated by Selenium IDE
from datetime import time

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
#录制的脚本
# coding = utf-8
from selenium import webdriver
driver =webdriver.Chrome()
driver.get('http://www.baidu.com')
driver.quit()

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.close()
    self.driver.get("https://www.baidu.com/index.php?tn=monline_3_dg")
    self.driver.set_window_size(1295, 695)
    self.driver.find_element(By.ID, "kw").send_keys("你在干啥")
    time.sleep(5)
    self.driver.find_element(By.ID, "kw").send_keys(Keys.ENTER)
    print("好了")
  
