# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogintest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  

  def test_logintest(self):
    self.driver.get("http://47.92.29.3:8080/onlinemusic/login.html")
    self.driver.set_window_size(1295, 695)
    self.driver.find_element(By.ID, "user").click()
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.ID, "user").send_keys("张雨蓉")
    self.driver.find_element(By.ID, "submit").click()

  def teardown_method(self, method):
    self.driver.quit()
